# Auto-labeler configuration for CCEM
# https://github.com/actions/labeler

# Main application
app:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/CCEM/**'

# Core libraries
core:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/CCEM.Core.*/**'

# UI assets and views
ui:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.xaml'
          - 'src/CCEM/Views/**'
          - 'src/CCEM/ViewModels/**'
          - 'src/CCEM/Themes/**'
          - 'src/CCEM/Assets/**'

# Tests
tests:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**/*.Tests/**'
          - 'src/**/TestInfrastructure/**'
          - 'src/**/Integration/**'
          - 'src/**/Unit/**'

# Documentation
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**'

# General source code (shared pieces)
source:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**/*.cs'
          - 'src/**/*.csproj'
          - 'src/**/*.sln*'
          - 'src/*.cs'
          - 'src/*.sln*'

# Dependencies and project metadata
dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/Directory.Build.props'
          - 'src/Directory.Build.targets'
          - 'src/**/*.csproj'

# CI / automation
ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'

# Repo configuration
config:
  - changed-files:
      - any-glob-to-any-file:
          - '.editorconfig'
          - '.gitignore'
          - 'src/.editorconfig'
          - 'src/settings.xamlstyler'
          - '.vscode/**'
