// -----------------------------------------------------------------------------------------------------
// | <auto-generated>                                                                                  |
// |    This code was generated by a tool.                                                             |
// |                                                                                                   |
// |    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. |
// | </auto-generated>                                                                                 |
// -----------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace CCEM;
public partial class BreadcrumbPageMappings
{
    public static Dictionary<Type, BreadcrumbPageConfig> PageDictionary = new()
    {
        {typeof(CCEM.Views.SettingsPage), new BreadcrumbPageConfig { PageTitle = null, IsHeaderVisible = true, ClearNavigation = false}},
        {typeof(CCEM.Views.AboutUsSettingPage), new BreadcrumbPageConfig { PageTitle = null, IsHeaderVisible = true, ClearNavigation = false}},
        {typeof(CCEM.Views.AppUpdateSettingPage), new BreadcrumbPageConfig { PageTitle = null, IsHeaderVisible = true, ClearNavigation = false}},
        {typeof(CCEM.Views.GeneralSettingPage), new BreadcrumbPageConfig { PageTitle = null, IsHeaderVisible = true, ClearNavigation = false}},
        {typeof(CCEM.Views.ThemeSettingPage), new BreadcrumbPageConfig { PageTitle = null, IsHeaderVisible = true, ClearNavigation = false}},
        {typeof(CCEM.Views.InventoryComponentsPage), new BreadcrumbPageConfig { PageTitle = "Components", IsHeaderVisible = true, ClearNavigation = false}},
        {typeof(CCEM.Views.InventoryCachePage), new BreadcrumbPageConfig { PageTitle = "Cache", IsHeaderVisible = true, ClearNavigation = false}},
        {typeof(CCEM.Views.InventoryInstalledSoftwarePage), new BreadcrumbPageConfig { PageTitle = "Installed software", IsHeaderVisible = true, ClearNavigation = false}},
        {typeof(CCEM.Views.InventoryEvaluationPage), new BreadcrumbPageConfig { PageTitle = "Evaluation", IsHeaderVisible = true, ClearNavigation = false}},
        {typeof(CCEM.Views.OperationsProcessesPage), new BreadcrumbPageConfig { PageTitle = "Processes", IsHeaderVisible = true, ClearNavigation = false}},
        {typeof(CCEM.Views.OperationsServicesPage), new BreadcrumbPageConfig { PageTitle = "Services", IsHeaderVisible = true, ClearNavigation = false}},
    };
}
