// -----------------------------------------------------------------------------------------------------
// | <auto-generated>                                                                                  |
// |    This code was generated by a tool.                                                             |
// |                                                                                                   |
// |    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. |
// | </auto-generated>                                                                                 |
// -----------------------------------------------------------------------------------------------------

// Define JSON folder path variable for easy adjustment

using System;
using System.Collections.Generic;

namespace CCEM;
public partial class NavigationPageMappings
{
    public static Dictionary<string, Type> PageDictionary { get; } = new Dictionary<string, Type>
    {
        {"CCEM.Views.Modules.IntuneLandingPage", typeof(CCEM.Views.Modules.IntuneLandingPage)},
        {"CCEM.Views.Modules.SccmLandingPage", typeof(CCEM.Views.Modules.SccmLandingPage)},

    };
}
