// -----------------------------------------------------------------------------------------------------
// | <auto-generated>                                                                                  |
// |    This code was generated by a tool.                                                             |
// |                                                                                                   |
// |    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. |
// | </auto-generated>                                                                                 |
// -----------------------------------------------------------------------------------------------------

// Define JSON folder path variable for easy adjustment
using System;
using System.Collections.Generic;

namespace CCEM;
public partial class NavigationPageMappings
{
    public static Dictionary<string, Type> PageDictionary { get; } = new Dictionary<string, Type>
    {
        {"CCEM.Views.Modules.IntuneLandingPage", typeof(CCEM.Views.Modules.IntuneLandingPage)},
        {"CCEM.Views.Modules.SccmLandingPage", typeof(CCEM.Views.Modules.SccmLandingPage)},
        {"CCEM.Views.Modules.SccmConnectionPage", typeof(CCEM.Views.Modules.SccmConnectionPage)},
        {"Sccm.AgentActions", typeof(CCEM.Views.Modules.SccmAgentActionsPage)},
        {"Sccm.AgentSettings", typeof(CCEM.Views.Modules.SccmAgentSettingsPage)},
        {"Sccm.SettingsMgmt", typeof(CCEM.Views.Modules.SccmSettingsMgmtPage)},
        {"Sccm.ServiceWindows", typeof(CCEM.Views.Modules.SccmServiceWindowsPage)},
        {"Sccm.InstalledSoftware", typeof(CCEM.Views.Modules.SccmInstalledSoftwarePage)},
        {"Sccm.EventMonitoring", typeof(CCEM.Views.Modules.SccmEventMonitoringPage)},
        {"Sccm.Advertisements", typeof(CCEM.Views.Modules.SccmAdvertisementsPage)},
        {"Sccm.SoftwareDistributionApps", typeof(CCEM.Views.Modules.SccmSoftwareDistributionAppsPage)},
        {"Sccm.Cache", typeof(CCEM.Views.Modules.SccmCachePage)},
        {"Sccm.Components", typeof(CCEM.Views.Modules.SccmComponentsPage)},
        {"Sccm.SoftwareDistributionSummary", typeof(CCEM.Views.Modules.SccmSoftwareDistributionSummaryPage)},
        {"Sccm.Services", typeof(CCEM.Views.Modules.SccmServicesPage)},
        {"Sccm.Processes", typeof(CCEM.Views.Modules.SccmProcessesPage)},
        {"Sccm.SoftwareUpdates", typeof(CCEM.Views.Modules.SccmSoftwareUpdatesPage)},
        {"Sccm.AllUpdates", typeof(CCEM.Views.Modules.SccmAllUpdatesPage)},
        {"Sccm.ExecutionHistory", typeof(CCEM.Views.Modules.SccmExecutionHistoryPage)},
        {"Sccm.InstallRepair", typeof(CCEM.Views.Modules.SccmInstallRepairPage)},
        {"Sccm.CollectionVariables", typeof(CCEM.Views.Modules.SccmCollectionVariablesPage)},
        {"Sccm.CcmEval", typeof(CCEM.Views.Modules.SccmCcmEvalPage)},
        {"Sccm.PowerSettings", typeof(CCEM.Views.Modules.SccmPowerSettingsPage)},
        {"Sccm.LogMonitoring", typeof(CCEM.Views.Modules.SccmLogsPage)},
        {"Sccm.WmiBrowser", typeof(CCEM.Views.Modules.SccmWmiBrowserPage)},
        {"Sccm.Tools", typeof(CCEM.Views.Modules.SccmToolsPage)},
    };
}
