// -----------------------------------------------------------------------------------------------------
// | <auto-generated>                                                                                  |
// |    This code was generated by a tool.                                                             |
// |                                                                                                   |
// |    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. |
// | </auto-generated>                                                                                 |
// -----------------------------------------------------------------------------------------------------

// Define JSON file path variable for easy adjustment
using System;
using System.Collections.Generic;

namespace CCEM;
public partial class NavigationPageMappings
{
    public static Dictionary<string, Type> PageDictionary { get; } = new Dictionary<string, Type>
    {
        {"CCEM.Views.HomeLandingPage", typeof(CCEM.Views.HomeLandingPage)},
        {"CCEM.Views.SCCM.ConnectionPage", typeof(CCEM.Views.SCCM.ConnectionPage)},
        {"SCCM.Overview", typeof(CCEM.Views.Shared.PlaceholderPage)},
        {"SCCM.Components", typeof(CCEM.Views.Shared.PlaceholderPage)},
        {"SCCM.AgentSettings", typeof(CCEM.Views.Shared.PlaceholderPage)},
        {"SCCM.InstallRepair", typeof(CCEM.Views.Shared.PlaceholderPage)},
        {"SCCM.InstallAgent", typeof(CCEM.Views.Shared.PlaceholderPage)},
        {"SCCM.Cache", typeof(CCEM.Views.Shared.PlaceholderPage)},
        {"SCCM.Applications", typeof(CCEM.Views.Shared.PlaceholderPage)},
        {"SCCM.InstalledSoftware", typeof(CCEM.Views.Shared.PlaceholderPage)},
        {"SCCM.Advertisements", typeof(CCEM.Views.Shared.PlaceholderPage)},
        {"SCCM.ExecutionHistory", typeof(CCEM.Views.Shared.PlaceholderPage)},
        {"SCCM.Updates", typeof(CCEM.Views.Shared.PlaceholderPage)},
        {"SCCM.AllUpdates", typeof(CCEM.Views.Shared.PlaceholderPage)},
        {"SCCM.UpdateStatus", typeof(CCEM.Views.Shared.PlaceholderPage)},
        {"SCCM.Services", typeof(CCEM.Views.Shared.PlaceholderPage)},
        {"SCCM.Processes", typeof(CCEM.Views.Shared.PlaceholderPage)},
        {"SCCM.Logs", typeof(CCEM.Views.Shared.PlaceholderPage)},
        {"SCCM.LogViewer", typeof(CCEM.Views.Shared.PlaceholderPage)},
        {"SCCM.EventMonitoring", typeof(CCEM.Views.Shared.PlaceholderPage)},
        {"SCCM.ServiceWindows", typeof(CCEM.Views.Shared.PlaceholderPage)},
        {"SCCM.Variables", typeof(CCEM.Views.Shared.PlaceholderPage)},
        {"SCCM.Power", typeof(CCEM.Views.Shared.PlaceholderPage)},
        {"SCCM.WMIBrowser", typeof(CCEM.Views.Shared.PlaceholderPage)},
        {"SCCM.Evaluation", typeof(CCEM.Views.Shared.PlaceholderPage)},
        {"SCCM.ImportApp", typeof(CCEM.Views.Shared.PlaceholderPage)},
        {"CCEM.Views.Intune.ComingSoonPage", typeof(CCEM.Views.Intune.ComingSoonPage)},
        {"CCEM.Views.SettingsPage", typeof(CCEM.Views.SettingsPage)},
        {"CCEM.Views.AboutUsSettingPage", typeof(CCEM.Views.AboutUsSettingPage)},
    };
}
