global using CCEM.Common;
global using CCEM.SCCM.Automation;
global using CCEM.SCCM.Models;
global using CCEM.ViewModels.SCCM;
global using CCEM.SCCM.Services;
global using CCEM.Shared.Helpers;
global using CCEM.ViewModels;
global using CCEM.Views;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using DevWinUI;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.UI;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Navigation;
global using static CCEM.Common.AppHelper;
global using static CCEM.Common.LoggerSetup;
