name: 🚀 Build Stable

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  stable:
    name: Stable
    uses: ./.github/workflows/build-and-release.yml
    with:
      source-branch: main
      release-channel: stable
      release-type: stable
      release-title-prefix: CCEM
    secrets: inherit
