name: 🚀 Build Stable

on:
  workflow_dispatch:

permissions:
  contents: write

# Environment variables
env:
  SOURCE_BRANCH: main
  VELOPACK_CHANNEL: stable
  RELEASE_TITLE_PREFIX: CCEM

jobs:
  stable:
    name: Stable
    uses: ./.github/workflows/build-and-release.yml
    with:
      source-branch: ${{ env.SOURCE_BRANCH }}
      release-channel: ${{ env.VELOPACK_CHANNEL }}
      release-type: stable
      release-title-prefix: ${{ env.RELEASE_TITLE_PREFIX }}
    secrets: inherit
