name: Build Stable Release

on:
  workflow_dispatch:

env:
  SOURCE_BRANCH: main

permissions:
  contents: write

jobs:
  derive_version:
    name: "🧮 Derive Stable Version"
    uses: ./.github/workflows/versioning.yml
    with:
      release_type: stable

  build_and_publish:
    name: "🚢 Build and Publish Stable Release"
    needs:
      - derive_version
    uses: ./.github/workflows/build-and-publish.yml
    with:
      branch: ${{ env.SOURCE_BRANCH }}
      version: ${{ needs.derive_version.outputs.version }}
      msix_version: ${{ needs.derive_version.outputs.msix_version }}
      tag: ${{ needs.derive_version.outputs.tag }}
      channel: ${{ needs.derive_version.outputs.channel }}
      prerelease: false
      release_name: ${{ needs.derive_version.outputs.release_name }}
      make_latest: "true"
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}
